/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs6420.sample_app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void appSayHello(){
        App app = new App();
        assertEquals("true", "True", "Not equals");
    }
}
